apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  labels:
  name: install-kwok-crb
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: install-kwok-clusterrole
subjects:
  - kind: ServiceAccount
    name: install-kwok
    namespace: default
