apiVersion: batch/v1
kind: Job
metadata:
  name: install-kwok
spec:
  template:
    spec:
      serviceAccountName: install-kwok
      containers:
      - name: install-kwok
        env:
        - name: POD_NAMESPACE
          valueFrom:
            fieldRef:
              fieldPath: metadata.namespace
        - name: SERVICE_ACCOUNT
          valueFrom:
            fieldRef:
              fieldPath: spec.serviceAccountName
        image: ghcr.io/vadafoss/install-kwok:debian4
      restartPolicy: Never
  backoffLimit: 4
   